#! /usr/bin/env python
#
# Vivek Rai
# vivekrai@umich.edu
# Parker Lab
#
# Jan 10, 2019
# GPL License

import sys
import os

import yaml
import docopt

doc = """
    json2yaml

    Converts JSON to YAML.

    Usage: json2yaml [<file>]

    Options:
    <file>   JSON file
"""

args = docopt.docopt(doc, version="0.1")


def jsontoyaml(file):
    """ Convert YAML to JSON.

    Specify FILE or input from STDIN.
    """
    with open(file, "r") as f:
        _json = yaml.safe_load(f)
    print(yaml.safe_dump(_json, default_flow_style=False, sort_keys=True, indent=4))


if __name__ == "__main__":
    json_file = args["<file>"]

    if json_file and not os.path.exists(json_file):
        print("File not found.")
        sys.exit(1)

    if not json_file:
        json_file = "/dev/stdin"

    jsontoyaml(json_file)
